package guiCountries;




import static guiCountries.Registro.listaUsuarios;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.Date;
import guiCountries.Paises;
import static guiCountries.Paises.reptranf;
import guiCountries.Registro;
import javax.swing.JOptionPane;

public class Mi_Cuenta extends javax.swing.JFrame {

    ArrayList<Paises> listaTrans = new ArrayList<>();
    DefaultTableModel trans;
    
    public Mi_Cuenta() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Mi Cuenta");
        trans = (DefaultTableModel) tbTransacciones.getModel();
        cargarRepTranf();
        setUsuario();
        setlbSaldo();
    }
    
//    public void cargarTabla (){
//        trans.setRowCount(0);
//                
////        for (int i=0 ; i < listaTrans.size(); i++ ){
////            trans.addRow(new Object[]{
////                listaTrans.get(i).get(),
////                listaTrans.get(i).getApellido(),
////                listaTrans.get(i).getCorreo(),
////                listaTrans.get(i).getUsuario(),
////                listaTrans.get(i).getRol(),
////              
////        });
////        }    
//}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnAtras = new javax.swing.JButton();
        btnRetirar = new javax.swing.JButton();
        txtMonto = new javax.swing.JTextField();
        btnDepositar = new javax.swing.JButton();
        lbMicuenta = new javax.swing.JLabel();
        lbUsuario = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbTransacciones = new javax.swing.JTable();
        lbTransacciones = new javax.swing.JLabel();
        lbS = new javax.swing.JLabel();
        lbsaldo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jLabel1.setText("Ingrese el monto ");

        btnAtras.setText("Atrrás");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        btnRetirar.setText("Retirar ");
        btnRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarActionPerformed(evt);
            }
        });

        txtMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoActionPerformed(evt);
            }
        });

        btnDepositar.setText("Depositar ");
        btnDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositarActionPerformed(evt);
            }
        });

        lbMicuenta.setFont(new java.awt.Font("Yu Gothic Light", 1, 36)); // NOI18N
        lbMicuenta.setText("Mi cuenta");

        lbUsuario.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lbUsuario.setText("Usuario");

        tbTransacciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "País", "Envio", "Moneda", "Monto", "Tarifa Destino", "Tarifa Servicio", "Total", "Fecha"
            }
        ));
        jScrollPane1.setViewportView(tbTransacciones);

        lbTransacciones.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lbTransacciones.setText("Transacciones ");

        lbS.setFont(new java.awt.Font("Yu Gothic Light", 1, 18)); // NOI18N
        lbS.setText("Saldo Actual:");

        lbsaldo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbsaldo.setText("monto del saldo ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(lbUsuario)
                        .addGap(198, 198, 198)
                        .addComponent(lbMicuenta)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAtras)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(81, 81, 81)
                                        .addComponent(jLabel1)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbS)
                                        .addGap(18, 18, 18)
                                        .addComponent(lbsaldo))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(btnRetirar)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnDepositar))
                                        .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(106, 106, 106)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTransacciones)
                .addGap(258, 258, 258))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(lbUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAtras))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(lbMicuenta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTransacciones, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbsaldo, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbS)
                        .addGap(56, 56, 56)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRetirar)
                            .addComponent(btnDepositar))
                        .addGap(135, 135, 135)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        Menu view= new Menu();
        view.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarActionPerformed
        
        for (int i = 0; i < listaUsuarios.size(); i++) {
            //este if compara el nombre de usuario logueado con los de la lista para encontrar su posicion en ella
            if (listaUsuarios.get(i).getUsuario().equalsIgnoreCase(Login.usuario)) {
                int saldo =listaUsuarios.get(i).getSaldo()- Integer.parseInt(txtMonto.getText());
                if (saldo>=0) {
                    listaUsuarios.get(i).setSaldo(saldo);
                    setlbSaldo();
                }else{
                    JOptionPane.showMessageDialog(null, "El monto de la transacción excede los fondos del usuario");
                }
                
            }
        }
        
    }//GEN-LAST:event_btnRetirarActionPerformed

    private void btnDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositarActionPerformed
        for (int i = 0; i < listaUsuarios.size(); i++) {
            //este if compara el nombre de usuario logueado con los de la lista para encontrar su posicion en ella
            if (listaUsuarios.get(i).getUsuario().equalsIgnoreCase(Login.usuario)) {
                int saldo =listaUsuarios.get(i).getSaldo()+ Integer.parseInt(txtMonto.getText());
                listaUsuarios.get(i).setSaldo(saldo);
                setlbSaldo();
            }
        }
    }//GEN-LAST:event_btnDepositarActionPerformed

    public void setlbSaldo(){
        for (int i = 0; i < listaUsuarios.size(); i++) {
            //este if compara el nombre de usuario logueado con los de la lista para encontrar su posicion en ella
            if (listaUsuarios.get(i).getUsuario().equalsIgnoreCase(Login.usuario)) {
                lbsaldo.setText(listaUsuarios.get(i).getSaldo()+"");
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mi_Cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mi_Cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mi_Cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mi_Cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mi_Cuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnDepositar;
    private javax.swing.JButton btnRetirar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbMicuenta;
    private javax.swing.JLabel lbS;
    private javax.swing.JLabel lbTransacciones;
    private javax.swing.JLabel lbUsuario;
    private javax.swing.JLabel lbsaldo;
    private javax.swing.JTable tbTransacciones;
    private javax.swing.JTextField txtMonto;
    // End of variables declaration//GEN-END:variables
 
//    public String saldo (){
//        
//        lbsaldo.setText(txtMonto);
//        return lbsaldo;
//    }
   public void cargarRepTranf (){
        trans.setRowCount(0);
        
        for (int i = 0; i < reptranf.size(); i++ ){
            if(reptranf.get(i).getUsuario().equalsIgnoreCase(Login.usuario)){
             trans.addRow(new Object[]{
             reptranf.get(i).getPaisdestino(),
             reptranf.get(i).getTipoenvio(),
             reptranf.get(i).getMonedaenvio(),
             reptranf.get(i).getMontoenv(),
             reptranf.get(i).getTarifdest(),
             reptranf.get(i).getTarifserv(),
             reptranf.get(i).getTottransf(),
             reptranf.get(i).getFecha(),
            });
            } 
        }
            
    }
   
   public void setUsuario(){
       lbUsuario.setText(Login.usuario);
   }
    
}
